version: '3'

services:
  postgres:
    image: postgres
    container_name: {{.ProjectName}}_postgres_local
    env_file:
      - ../../envs/{{.ProjectName}}/local.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
